# Generated by Django 5.1.6 on 2025-03-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_list_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
