# Generated by Django 5.1.6 on 2025-03-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='combo_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='combo_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
